<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE programmdaten [<!-- Technische Ausstrahlungsattribute --><!ENTITY mo "mono"><!ENTITY st "stereo"><!ENTITY zk "zweikanalton"><!ENTITY ot "originalton"><!ENTITY ds "dolby"><!ENTITY dd "dolbydigital"><!ENTITY sw "schwarzweiß"><!ENTITY f43 "4zu3"><!ENTITY f16 "16zu9"><!ENTITY bw "breitwand"><!ENTITY vo "videotext"><!ENTITY ad "audiodeskription"><!ENTITY gs "gebaerdensprache"><!ENTITY mhp "mhp"><!ENTITY hd "highdefinition"><!-- Programmdaten eines Senders für eine Programmwoche--><!ELEMENT programmdaten (sendetag)+><!ATTLIST programmdaten sender CDATA #REQUIRED woche CDATA #REQUIRED erstelldatum CDATA #REQUIRED><!-- Sendungen eines Sendetages --><!ELEMENT sendetag (sendung)+><!ATTLIST sendetag datum CDATA #REQUIRED thementag CDATA #IMPLIED><!-- Detaildaten zur Sendung --><!ELEMENT sendung (id,(ausstrahlung), (programm))><!ELEMENT sendung (id,(ausstrahlung), (streamingportal), (programm))><!-- ID der Sendung --><!ELEMENT id (#PCDATA)><!ELEMENT ausstrahlung (startzeit, biszeit, endezeit?,dauermin, vps?, veranst?, attribute?, hinweis*)><!ELEMENT streamingportal (verweildauerVon?, verweildauerBis?)><!ELEMENT programm (label?, sendetitel, folgentitel?,folgenr?, staffel?, stafonr?, untertitel*, originaltitel?,reihe?, sportstrecke?, zusatz*, moderation*, progart?, kategorie?,thember?, genre?, herkunftsender?,land*, jahr?, hinweis*, erstsendung?,wiederhvom?, erstausstr?, (besetzung)?, regie*, drehbuch*,musik*, filmvon*, gast*, (stab)?, (programmtext)?, (pressetext)?, (pressebilder)?, beitrag*)><!-- Beginnzeit: Datum + Zeit yyyy.mm.ddThh.mm.ss--><!ELEMENT startzeit (#PCDATA)><!-- circa Zeitangabe: anschließend, gegen, dazwischen --><!ATTLIST startzeit cazeit CDATA #IMPLIED><!-- Endezeit dieser Sendung  --><!ELEMENT biszeit (#PCDATA)><!-- Ende des Sendetages --><!ELEMENT endezeit (#PCDATA)><!-- Dauer in Minuten  --><!ELEMENT dauermin (#PCDATA)><!-- vps-Zeit hh:mm --><!ELEMENT vps (#PCDATA)><!-- Sonderveranstaltung: Olympiade, Fußball, IfA --><!ELEMENT veranst (#PCDATA)><!-- Technische Attribute: Ton, Bildformat etc.--><!ELEMENT attribute (#PCDATA)><!-- Streaming-Portal verweildauerVon: Datum yyyy.mm.ddThh.mm.ss--><!ELEMENT verweildauerVon (#PCDATA)><!-- Streaming-Portal verweildauerBis: Datum yyyy.mm.ddThh.mm.ss--><!ELEMENT verweildauerBis (#PCDATA)><!-- Dachzeile/Label --><!ELEMENT label (#PCDATA)><!-- Sendetitel --><!ELEMENT sendetitel (#PCDATA)><!-- Folgentitel bei Reihen und Serien --><!ELEMENT folgentitel (#PCDATA)><!-- Nummer der Folge (Reihen und Serien) --><!ELEMENT folgenr (#PCDATA)><!-- Nummer der Staffel (Reihen und Serien) --><!ELEMENT staffel (#PCDATA)><!-- Folgenummer innerhalb der Staffel --><!ELEMENT stafonr (#PCDATA)><!-- Unterzeile (Subtitle) --><!ELEMENT untertitel (#PCDATA)><!-- Originaltitel --><!ELEMENT originaltitel (#PCDATA)><!-- aus der Reihe... --><!ELEMENT reihe (#PCDATA)><!-- Unterablauf Sportstrecke inkl. Unterbrechersendung --><!-- Unterablauf Sportstrecke inkl. Unterbrechersendung --><!ELEMENT sportstrecke (event*, textsport*, ablaufhinweis?)><!ELEMENT event (#PCDATA | br)*><!ATTLIST event beginn CDATA #IMPLIED typ CDATA #REQUIRED group CDATA #IMPLIED top CDATA #IMPLIED><!ELEMENT textsport (#PCDATA)><!ELEMENT ablaufhinweis (#PCDATA)><!-- zusätzliche Angaben zum Titel--><!ELEMENT zusatz (#PCDATA)><!-- Name des Moderators --><!ELEMENT moderation (#PCDATA)><!-- Programmart (Subkategorie) --><!ELEMENT progart (#PCDATA)><!-- Programmkategorie --><!ELEMENT kategorie (#PCDATA)><!-- Themenbereich --><!ELEMENT thember (#PCDATA)><!-- Fiktionales Genre --><!ELEMENT genre (#PCDATA)><!-- Herkunftsender --><!ELEMENT herkunftsender (#PCDATA)><!-- Herkunftsland --><!ELEMENT land (#PCDATA)><!ATTLIST land kfz CDATA #IMPLIED><!-- Herstellungsjahr --><!ELEMENT jahr (#PCDATA)><!-- Bemerkung zur Sendung --><!ELEMENT hinweis (#PCDATA)><!-- Datum der Erstausstrahlung --><!ELEMENT erstsendung (#PCDATA)><!-- Wiederholung vom .. --><!ELEMENT wiederhvom (#PCDATA)><!-- Erstausstrahlung ja/nein --><!ELEMENT erstausstr (#PCDATA)><!-- Besetzung (Darsteller) --><!ELEMENT besetzung (darsteller*)><!ELEMENT darsteller (#PCDATA)><!ATTLIST darsteller rolle CDATA #REQUIRED><!-- Mitwirkende (Stabliste) --><!ELEMENT regie (#PCDATA)><!ELEMENT drehbuch (#PCDATA)><!ELEMENT musik (#PCDATA)><!ELEMENT filmvon (#PCDATA)><!ELEMENT gast (#PCDATA)><!-- Stabliste (Funktion und Name --><!ELEMENT stab (person*)><!ELEMENT person (#PCDATA)><!ATTLIST person funktion CDATA #REQUIRED><!ELEMENT programmtext (kurztext?, fortsetzung1?, fortsetzung2?, begleittext?, themagastfolge*)><!ELEMENT kurztext (#PCDATA | br)*><!ELEMENT fortsetzung1 (#PCDATA | br)*><!ELEMENT fortsetzung2 (#PCDATA | br)*><!ELEMENT begleittext (#PCDATA | br)*><!ELEMENT themagastfolge (#PCDATA | br)*><!ATTLIST themagastfolge 		titel CDATA #REQUIRED><!-- Beschreibung Programminhalt --><!ELEMENT pressetext (#PCDATA | p)*><!-- Absatz --><!ELEMENT p (#PCDATA)><!-- Zeilenumbruch --><!ELEMENT br EMPTY><!-- Fotos zur Sendung, lfdnr 001 ist das Hauptbild --><!ELEMENT pressebilder (pressebild*, bild*)><!ELEMENT pressebild (#PCDATA)><!-- Hauptbild Bildformat 16:9 in div. Größen --><!-- weitere Pressebilder in Standardgrößen --><!-- normal = 1920 Pixel an der längsten Seite --><!-- preview = 675 Pixel an der längsten Seite --><!-- thumbnail = 250 Pixel an der längsten Seite --><!ELEMENT bild (urlbild*)><!ATTLIST bild lfdnr CDATA #REQUIRED><!ELEMENT urlbild (#PCDATA)><!ATTLIST urlbild layout (normal | preview | thumbnail) #REQUIRED><!-- Sendungsbeitrag --><!ELEMENT beitrag (#PCDATA)>]>
<programmdaten sender="3sat" woche="202616" erstelldatum="06.03.2026 08:09:12">
  <sendetag datum="11.04.2026">
    <sendung>
      <id>765323c5-6804-429b-86ca-1bcc85fc904d</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T06:20:00</startzeit>
        <biszeit>2026.04.11T07:00:00</biszeit>
        <dauermin>40</dauermin>
        <vps />
        <attribute>&amp;hd; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>Kulturzeit</sendetitel>
        <folgentitel />
        <untertitel>Das 3sat-Kulturmagazin von ZDF, ORF, SRF und ARD</untertitel>
        <originaltitel />
        <sportstrecke />
        <moderation>Lilian Moschen</moderation>
        <progart>Magazin</progart>
        <kategorie>Kultur</kategorie>
        <thember>Kultur allgemein</thember>
        <herkunftsender>3sat</herkunftsender>
        <erstsendung>10.04.2026</erstsendung>
        <programmtext>
          <kurztext>"Kulturzeit" ist das werktägliche Kulturmagazin von 3sat.</kurztext>
          <fortsetzung1>"Kulturzeit" mischt sich in kulturelle und gesellschaftspolitische Fragen ein. Das Magazin bietet Hintergrundinformationen, Porträts und Gespräche zu aktuellen und brisanten Fragen.</fortsetzung1>
        </programmtext>
        <pressetext>&lt;p&gt;"Kulturzeit" ist das werktägliche Kulturmagazin von 3sat.&lt;br/&gt;&lt;br/&gt;"Kulturzeit" mischt sich in kulturelle und gesellschaftspolitische Fragen ein. Das Magazin bietet Hintergrundinformationen, Porträts und Gespräche zu aktuellen und brisanten Fragen.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/c22ab4c1-08b0-4867-9191-479f6852bb63?layout=thumbnail</urlbild>
          </bild>
        </pressebilder>
      </programm>
    </sendung>
    <sendung>
      <id>37d29396-d701-43c7-8f1d-1bcc85fcad85</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T07:00:00</startzeit>
        <biszeit>2026.04.11T07:30:00</biszeit>
        <dauermin>30</dauermin>
        <vps />
        <attribute>&amp;hd; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>nano</sendetitel>
        <folgentitel />
        <untertitel>Die Welt von morgen</untertitel>
        <originaltitel />
        <sportstrecke />
        <moderation>Gregor Steinbrenner</moderation>
        <progart>Magazin</progart>
        <kategorie>Wissenschaft, Technik und Umwelt</kategorie>
        <thember>Naturwissenschaften</thember>
        <herkunftsender>3sat</herkunftsender>
        <erstsendung>09.04.2026</erstsendung>
        <programmtext>
          <kurztext>Das 3sat-Wissenschaftsmagazin berichtet ausführlich, verständlich und aktuell über Technik, Medizin, Wissenschaft und Forschung.</kurztext>
          <fortsetzung1>"nano" macht Zukunftsvisionen sichtbar und erfahrbar. Durch eine unterhaltsame, spannende und informative Mischung von Wissenschaftsfilmen macht "nano" seine Zuschauer fit für die Welt von morgen.</fortsetzung1>
          <fortsetzung2>"nano" ist ein aktuelles Magazin und enthält Studio- und Schaltgespräche. Regelmäßig werden Schwerpunkte gesetzt und wissenschaftlich beleuchtet.</fortsetzung2>
        </programmtext>
        <pressetext>&lt;p&gt;Das 3sat-Wissenschaftsmagazin berichtet ausführlich, verständlich und aktuell über Technik, Medizin, Wissenschaft und Forschung.&lt;br/&gt;&lt;br/&gt;"nano" macht Zukunftsvisionen sichtbar und erfahrbar. Durch eine unterhaltsame, spannende und informative Mischung von Wissenschaftsfilmen macht "nano"  seine Zuschauer fit für die Welt von morgen.&lt;br/&gt;&lt;br/&gt;"nano" ist ein aktuelles Magazin und enthält Studio- und Schaltgespräche. Regelmäßig werden Schwerpunkte gesetzt und wissenschaftlich beleuchtet.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/47eb8abe-d4c3-47f8-ad4b-4f3002923cee?layout=thumbnail</urlbild>
          </bild>
        </pressebilder>
      </programm>
    </sendung>
    <sendung>
      <id>1377b053-911b-4915-a891-1bcc85fccd56</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T07:30:00</startzeit>
        <biszeit>2026.04.11T09:00:00</biszeit>
        <dauermin>90</dauermin>
        <vps />
        <attribute>&amp;hd; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>Alpenpanorama</sendetitel>
        <folgentitel />
        <originaltitel />
        <sportstrecke />
        <progart>Übertragung</progart>
        <kategorie>Sonstige Sendungen</kategorie>
        <thember>Reisen/Urlaub/Touristik</thember>
        <herkunftsender>ORF/3sat</herkunftsender>
        <erstsendung />
        <programmtext>
          <kurztext>"Alpenpanorama" zeigt über zahlreiche Web- und Panoramakameras täglich Livebilder aus ausgewählten Urlaubsorten.</kurztext>
          <fortsetzung1>Die Sendung informiert auch über Temperatur- und Wetterbedingungen vor Ort.</fortsetzung1>
        </programmtext>
        <pressetext>&lt;p&gt;"Alpenpanorama" zeigt über zahlreiche Web- und Panoramakameras täglich Livebilder aus ausgewählten Urlaubsorten.&lt;br/&gt;&lt;br/&gt;Die Sendung informiert auch über Temperatur- und Wetterbedingungen vor Ort.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/8dfb4c67-0576-4c4e-b7fe-caa0edbcde88?layout=thumbnail</urlbild>
          </bild>
        </pressebilder>
      </programm>
    </sendung>
    <sendung>
      <id>2be1acbe-4cdc-4fcc-94d8-1bcc85fd23f4</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T09:00:00</startzeit>
        <biszeit>2026.04.11T09:05:00</biszeit>
        <dauermin>5</dauermin>
        <vps />
        <attribute>&amp;hd; &amp;vo; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>ZIB</sendetitel>
        <folgentitel />
        <originaltitel />
        <sportstrecke />
        <progart>Nachrichten</progart>
        <kategorie>Nachrichten</kategorie>
        <thember>gemischte Themen</thember>
        <herkunftsender>ORF</herkunftsender>
        <erstsendung />
        <programmtext>
          <kurztext>Die Kurzausgaben der österreichischen Nachrichtensendung "Zeit im Bild" (ZIB) liefern neben klassischen Nachrichten Informationen über Entwicklungen auf den Finanzmärkten und Expertenanalysen.</kurztext>
        </programmtext>
        <pressetext>&lt;p&gt;Die Kurzausgaben der österreichischen Nachrichtensendung "Zeit im Bild" (ZIB) liefern neben klassischen Nachrichten Informationen über Entwicklungen auf den Finanzmärkten und Expertenanalysen.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/5b5d3e55-7285-4f50-aa5c-b64b350c5a40?layout=thumbnail</urlbild>
          </bild>
        </pressebilder>
      </programm>
    </sendung>
    <sendung>
      <id>a12f22e3-74e7-44ac-aa57-1bcc85fd6e53</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T09:05:00</startzeit>
        <biszeit>2026.04.11T09:35:00</biszeit>
        <dauermin>30</dauermin>
        <vps />
        <attribute>&amp;hd; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>Kulturplatz</sendetitel>
        <folgentitel />
        <untertitel>Das Kulturmagazin von Schweizer Radio und Fernsehen</untertitel>
        <originaltitel />
        <sportstrecke />
        <moderation>Eva Wannenmacher</moderation>
        <progart>Magazin</progart>
        <kategorie>Kultur</kategorie>
        <thember>Kultur allgemein</thember>
        <herkunftsender>SRF</herkunftsender>
        <erstsendung>08.04.2026</erstsendung>
        <programmtext>
          <kurztext>Hinein ins pralle Leben: "Kulturplatz" greift auf, was die Menschen beschäftigt, welche Fragen sie sich stellen. Und zeigt, dass die Kultur Antworten gibt.</kurztext>
          <fortsetzung1>"Kulturplatz" findet mitten im Leben statt: im Supermarkt, am Musikfestival, im Wald. Denn Kultur ist viel mehr als Musik, Literatur und Kunst. Kultur durchdringt unser Leben. Wo jemand nachzudenken beginnt, da entsteht Kultur.</fortsetzung1>
          <fortsetzung2>Diesem Credo ist "Kulturplatz" verpflichtet. Die Sendung will für Kultur begeistern und behält dabei die wichtigsten Akteure und Ereignisse des Kulturbetriebes im Blick. "Kulturplatz" spürt Trends auf und präsentiert Neuentdeckungen.</fortsetzung2>
        </programmtext>
        <pressetext>&lt;p&gt;Hinein ins pralle Leben: "Kulturplatz" greift auf, was die Menschen beschäftigt, welche Fragen sie sich stellen. Und zeigt, dass die Kultur Antworten gibt.&lt;br/&gt;&lt;br/&gt;"Kulturplatz" findet mitten im Leben statt: im Supermarkt, am Musikfestival, im Wald. Denn Kultur ist viel mehr als Musik, Literatur und Kunst. Kultur durchdringt unser Leben. Wo jemand nachzudenken beginnt, da entsteht Kultur.&lt;br/&gt;&lt;br/&gt;Diesem Credo ist "Kulturplatz" verpflichtet. Die Sendung will für Kultur begeistern und behält dabei die wichtigsten Akteure und Ereignisse des Kulturbetriebes im Blick. "Kulturplatz" spürt Trends auf und präsentiert Neuentdeckungen.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/27c000c7-2ae6-4508-a7fc-09569052d60a?layout=thumbnail</urlbild>
          </bild>
        </pressebilder>
      </programm>
    </sendung>
    <sendung>
      <id>eac664ca-341f-48cf-9a95-1bcc85fdbb82</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T09:35:00</startzeit>
        <biszeit>2026.04.11T10:00:00</biszeit>
        <dauermin>25</dauermin>
        <vps />
        <attribute>&amp;hd; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>Bilder aus Südtirol</sendetitel>
        <folgentitel />
        <originaltitel />
        <sportstrecke />
        <progart>Magazin</progart>
        <kategorie>Regionalinformation</kategorie>
        <thember>gemischte Themen</thember>
        <herkunftsender>ORF/3sat</herkunftsender>
        <erstsendung />
        <programmtext>
          <kurztext>"Bilder aus Südtirol" ist das Bundesländermagazin des ORF-Landesstudios Tirol.</kurztext>
          <fortsetzung1>Die Dokumentationen stellen die Kultur und das gesellschaftspolitische Geschehen in Südtirol vor.</fortsetzung1>
        </programmtext>
        <pressetext>&lt;p&gt;"Bilder aus Südtirol" ist das Bundesländermagazin des ORF-Landesstudios Tirol.&lt;br/&gt;&lt;br/&gt;Die Dokumentationen stellen die Kultur und das gesellschaftspolitische Geschehen in Südtirol vor.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/7d4b2a51-e894-405f-98be-8a37c81117df?layout=thumbnail</urlbild>
          </bild>
        </pressebilder>
      </programm>
    </sendung>
    <sendung>
      <id>b04cd6e7-79ea-43dd-af8f-1cca4b70badb</id>
      <ausstrahlung>
        <startzeit cazeit="">2026.04.11T10:00:00</startzeit>
        <biszeit>2026.04.11T10:45:00</biszeit>
        <dauermin>45</dauermin>
        <vps />
        <attribute>&amp;hd; &amp;vo; </attribute>
      </ausstrahlung>
      <streamingportal />
      <programm>
        <label />
        <sendetitel>Österreichs historische Gartenpracht (1/2)</sendetitel>
        <folgentitel />
        <untertitel>Film von Judith Doppler und Kurt Mayer</untertitel>
        <untertitel>(aus der ORF-III-Reihe "Erbe Österreich")</untertitel>
        <originaltitel />
        <sportstrecke />
        <progart>Dokumentation</progart>
        <kategorie>Kultur</kategorie>
        <thember>Architektur, Städtebau, Denkmalschutz</thember>
        <herkunftsender>ORF</herkunftsender>
        <erstsendung>25.12.2021</erstsendung>
        <programmtext>
          <kurztext>Österreichs barocke Gärten sind bis heute das Sinnbild der einstigen Macht und Größe ihrer Besitzer. Der alternde Prinz Eugen (1663-1736) interessierte sich mehr für Pflanzen als Schlachten.</kurztext>
          <fortsetzung1>An wichtigen Häfen, etwa Genua oder Venedig, hatte er Agenten platziert, die exotische Pflanzen beim Abladen für ihn zur Seite schafften. In Schloss Hof fand die Gartenliebe des Prinzen ihre ultimative Ausformung. Doch Prinz Eugen erlebte die Vollendung nicht mehr.</fortsetzung1>
          <fortsetzung2>Judith Doppler und Kurt Mayer haben sich auf die Spuren der Geschichten hinter Österreichs Gartenerbe gemacht. In Beauty-Shots, Reenactments und Interviews lassen sie eine Epoche wiederauferstehen, in der einige der beeindruckendsten Bauten und Anlagen Österreichs entstanden sind.</fortsetzung2>
        </programmtext>
        <pressetext>&lt;p&gt;Österreichs barocke Gärten sind bis heute das Sinnbild der einstigen Macht und Größe ihrer Besitzer. Der alternde Prinz Eugen (1663-1736) interessierte sich mehr für Pflanzen als Schlachten.&lt;br/&gt;&lt;br/&gt;An wichtigen Häfen, etwa Genua oder Venedig, hatte er Agenten platziert, die exotische Pflanzen beim Abladen für ihn zur Seite schafften. In Schloss Hof fand die Gartenliebe des Prinzen ihre ultimative Ausformung. Doch Prinz Eugen erlebte die Vollendung nicht mehr.&lt;br/&gt;&lt;br/&gt;Judith Doppler und Kurt Mayer haben sich auf die Spuren der Geschichten hinter Österreichs Gartenerbe gemacht. In Beauty-Shots, Reenactments und Interviews lassen sie eine Epoche wiederauferstehen, in der einige der beeindruckendsten Bauten und Anlagen Österreichs entstanden sind.&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;</pressetext>
        <pressebilder>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=2400x1350</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=1920x1080</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=1280x720</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=768x432</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=384x216</pressebild>
          <pressebild>http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=276x155</pressebild>
          <bild lfdnr="1">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/50666504-a819-42a4-a817-0fc8cffc20fb?layout=thumbnail</urlbild>
          </bild>
          <bild lfdnr="2">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/400c6ebe-250c-4aef-92c6-bab255a351ce?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/400c6ebe-250c-4aef-92c6-bab255a351ce?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/400c6ebe-250c-4aef-92c6-bab255a351ce?layout=thumbnail</urlbild>
          </bild>
          <bild lfdnr="3">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/3b4f7e77-c37b-46d8-87bc-e6354450f0a7?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/3b4f7e77-c37b-46d8-87bc-e6354450f0a7?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/3b4f7e77-c37b-46d8-87bc-e6354450f0a7?layout=thumbnail</urlbild>
          </bild>
          <bild lfdnr="4">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/d3ade320-5d59-47ad-bf53-eb7165231a85?layout=normal</urlbild>
            <urlbild layout="preview">http://epg-image.zdf.de/fotobase-webdelivery/images/d3ade320-5d59-47ad-bf53-eb7165231a85?layout=preview</urlbild>
            <urlbild layout="thumbnail">http://epg-image.zdf.de/fotobase-webdelivery/images/d3ade320-5d59-47ad-bf53-eb7165231a85?layout=thumbnail</urlbild>
          </bild>
          <bild lfdnr="5">
            <urlbild layout="normal">http://epg-image.zdf.de/fotobase-webdelivery/images/42258c7d-7829-4e21-b572-fcacc6d72fa4?layout=normal</urlbild>